### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Ac3n34d-X** [kuburan/txtool#3]
bash: ./install.py: /data/data/com.termux/files/usr/bin/python2: bad interpreter: No such file or directory

**Comment by kuburan** [comment]
require python 2 , not python 3.
```
python2 ./install.py
```

**Comment by Ac3n34d-X** [comment]
Kali default python is 2 and that's what I used

**Comment by kuburan** [comment]
oops, sorry currently it's not support on kali nor another distro.
txtool only support on android phone that already installing  Termux apps

**Comment by Ac3n34d-X** [comment]
Oh
